version: 0.2

phases:
  install:
    commands:
      - echo Installing nginx...
      - sudo apt-get update
      - sudo apt-get install -y nginx
  build:
    commands:
      - echo build started date on "date"
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Build phase - nothing to do here

artifacts:
  files:
    - /var/www/html/index.html
