version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing nginx...
      - sudo apt-get update
      - sudo apt-get install -y nginx

  build:
    commands:
      - echo Build phase - nothing to do here

artifacts:
  files:
    - /var/www/html/index.html
